services:
  jekyll:
    image: jekyll/jekyll:stable
    #command: jekyll serve --watch --incremental
    command: jekyll serve --livereload
    ports:
        - 4000:4000
    volumes:
        - .:/srv/jekyll
